### PR TITLE
--check-word: Try to highlight where it starts to differ

### PR DESCRIPTION
**Pull request by BoboTiG**
@lasconic what do you think about that? It could improve a lot our tasks.

Preview:
after

### CODE REVIEW

**Comment by BoboTiG** [comment]
@lasconic the color is just an example and I a open to review the output style ;)

**Comment by lasconic** [comment]
It's brilliant. Maybe test the last char of pattern for each iteration and continue if it's a space ? to avoid one call to contains per space ?

**Comment by BoboTiG** [comment]
Nice idea :+1:

**Comment by BoboTiG** [comment]
I've finished on my side. Is it good for you too?

**Comment by lasconic** [comment]
Yes ! go for it

**Pull request merged**
