### PR TITLE
[EN] Enhance support for 'm' and 'l' templates (closes #347)

### LINKED ISSUE #347: [EN] Enhance support for the 'm' template
- Wiktionary page: 

Wikicode:
```
{{m|ar|عِرْق||root}}
```

Output:
```
<b>عِرْق</b> (“root”)
```

Expected:
```
<b>عِرْق</b>‎ (<i>ʿirq</i>, “root”)
```

---

Model link: https://en.wiktionary.org/wiki/Template:mention

### PR DESCRIPTION
**Pull request by BoboTiG**
Ex: https://en.wiktionary.org/wiki/Iraq

- [x] Fixes #347
- [x] Tests added/updated.
- [x] `./check.sh` run and eventual issues fixed.
- [x] Updated CONTRIBUTORS.md, if not already done in the past.

### CODE REVIEW

**Comment by BoboTiG** [comment]
Well, transliterated texts are not exactly the same as on the Wiktionary because of missing characters. But we ar equite good as-is IMO. Also, the handling of such template is too complex, I would be open-minded for a better approach :)

**Review by lasconic — APPROVED** [review]

**Comment by lasconic** [comment]
Well no, I don't approve :) the unit tests are failing

**Comment by BoboTiG** [comment]
And you are right :)

Also I did not push all the latest changes... So let's retry in a few minutes haha

**Comment by BoboTiG** [comment]
Good to go :)

**Pull request merged**
