### PR TITLE
Improve CI runtime by caching APT packages

### LINKED ISSUE #1427: Use a custom docker image for tests
For each PR tests job, most of the time is taken by LateX installation. For instance, it takes about 2m40s to install it against 30s to run tests.

Maybe should we investigate the creation of a custom Docker image with LaTeX preinstalled. If so, I would be in favor of using a Debian-based **light** distribution, but I am open to any distribution as soon as tests are passing as-is (e.g: no modifications to be done on the source code).

### PR DESCRIPTION
**Pull request by BoboTiG**
Fixes #1427.

### CODE REVIEW

**Comment by BoboTiG** [comment]
Results are very satisfying!

- before: [4m 7s](https://github.com/BoboTiG/ebook-reader-dict/actions/runs/3471430860/jobs/5800912435)
- after: [23s](https://github.com/BoboTiG/ebook-reader-dict/actions/runs/3471430860/jobs/5801018693)

But that doesn't work :)

**Comment by BoboTiG** [comment]
Using actions/cache doesn't work with APT cache: https://github.com/actions/cache/issues/324.

**Comment by lasconic** [comment]
Interesting, it means downloading takes most of the time ? If yes, then it would be the same with docker and we would need to cache to docker image :)

**Comment by BoboTiG** [comment]
Well, last try with `apt-fast`.

**Pull request closed without merging**
