### PR TITLE
[DE] initial support for variants

### PR DESCRIPTION
**Pull request by tjaderxyz**
This is an initial support for variants in German. It currently parses three templates, `Grundformverweis Konj`, `Grundformverweis Dekl` and `Alte Schreibweise`, which should handle conjugated verbs, declined words and former spellings.

### CODE REVIEW

**Review by BoboTiG — APPROVED** [review]
Thanks a lot!

**Comment by BoboTiG** [comment]
Do you mind adding at least one test in `test_de.py`?

**Comment by tjaderxyz** [comment]
I added two test cases, one for `Gundformverweis *`, and one for `Alte Schreibweise`.

**Comment by BoboTiG** [comment]
That's perfecc!

**Comment by BoboTiG** [comment]
@all-contributors please add @tjaderxyz for code

**Pull request merged**
