### PR TITLE
fix #136: [CA] Add etymology

### LINKED ISSUE #136: [CA] Add etymology
Add etymologies for the catalan locale.

Models:
- [-etimologia-](https://ca.wiktionary.org/wiki/Plantilla:-etimologia-)

### PR DESCRIPTION
**Pull request by lasconic**
My python is rusty for sure... Please correct me if possible. 
It seems to work on the few cases I tested but I didn't test on the full dictionary yet.

### CODE REVIEW

**Review by BoboTiG — COMMENTED** [review]
Thanks a lot @lasconic :)

I would prefer to seprate fixes here (in separate PRs to ease reviewing), if you mind:
- I opened #177, #178 and #179 for template specific stuff.
- About the added langs, did you find a wikipage where they are all listed? It would ease syncing with future changes and can be automated (see specific "Parsing the languages list" wiki pages for examples).
- Side note: when you can, use doctest and remove duplicate tests from `test_ca.py`.

I would love to review PRs for templates listed above, when it will be much easier to review the specific catalan etymology part.

**Comment by BoboTiG** [comment]
Also, before doing more work (I really appreciate the effort), rebase yourself on master (I pushed changes minutes ago).

**Comment by lasconic** [comment]
Ok. I will then do 1 PR at a time and wait for each one to be merged before working on the next one.
Here is the first one : https://github.com/BoboTiG/ebook-reader-dict/pull/180

**Comment by BoboTiG** [comment]
Superseded by #184.

**Pull request closed without merging**
