### PR TITLE
[PT] Add "Imagem" to ignored namespaces

### LINKED ISSUE #1608: [PT] Add "Imagem" to ignored namespaces
- Wiktionary page: https://pt.wiktionary.org/wiki/maced%C3%B3nio

Wikicode:
```
[[Imagem:Flag of Macedonia.svg|20px]]
```

### PR DESCRIPTION
**Pull request by BoboTiG**
Fixes #1608

@lasconic OK with such change, or do you see a way to retrieve that namespace alias automatically maybe?

### CODE REVIEW

**Comment by lasconic** [comment]
Mmm so we need Imagem but not Image (in english or french) ?

**Comment by BoboTiG** [comment]
No, we need both `Ficheiro`, and `Imagem`, for Portuguese. For now it's the only exception I found.

**Comment by lasconic** [comment]
Interesting. There is a list of alias for EN here : https://en.wiktionary.org/wiki/Wiktionary:Namespace#Aliases

Image is an alias of File.

**Comment by lasconic** [comment]
And here is the API call to get the aliases : https://pt.wiktionary.org/w/api.php?action=query&meta=siteinfo&siprop=namespacealiases

I guess we could add for all languages the aliases of File and Category.

**Comment by BoboTiG** [comment]
Great, I'm on it!

**Pull request merged**
