### PR TITLE
[FR] Better handle the 'date' template (closes #196)

### LINKED ISSUE #196: [FR] Better handle the 'date' template
- Wiktionary page: https://fr.wiktionary.org/wiki/lune

Wikicode:
```
{{date|lang=fr|vers 980}}
```

Output:
```
(vers 980)
```

Expected:
```
(Vers 980)
```

### PR DESCRIPTION
**Pull request by BoboTiG**
Ex: https://fr.wiktionary.org/wiki/lune

- [x] Fixes #196
- [x] Tests added/updated.
- [x] `./check.sh` run and eventual issues fixed.
- [x] Updated CONTRIBUTORS.md, if not already done in the past.

### CODE REVIEW

**Comment by lasconic** [comment]
It will only work if there are no capitals in the text since capitalize() will lowercase everything but the first letter.

**Comment by BoboTiG** [comment]
Good catch, I updated the PR.

**Comment by lasconic** [comment]
LGTM

**Review by lasconic — COMMENTED** [review]
LGTM

**Review by lasconic — APPROVED** [review]
LGTM

**Pull request merged**
