### PR TITLE
Implement convert step, add DF file support

### PR DESCRIPTION
**Pull request by lasconic**
- [ ] Fixes #
- [ ] Tests added/updated.
- [ ] `./check.sh` run and eventual issues fixed.
- [ ] Updated CONTRIBUTORS.md, if not already done in the past.

### CODE REVIEW

**Comment by lasconic** [comment]
This is not complete yet. In particular, DF files don't store multiple time the same definition for form of verbs (not sure if it's necessary yet)
I used the resulting DF file with pyglossary to create startdict files and read it with Koreader (http://koreader.rocks/), it kinds of work (no image, no numbered list, but unicode support "out of the box")

**Comment by lasconic** [comment]
I did another test with variants. Conversion to stardict works and variants are used even if the prefix is different. Search is slow though... So the case "suis" ->être is handled (but not suis -> suivre..., apparently an single variant is found). 
We will probably need the fix from https://github.com/BoboTiG/ebook-reader-dict/issues/208 though because right now "minutes" only matches "minuter"

**Comment by lasconic** [comment]
In term of features, I would not add more. If the structure is OK, it can be merged and tests need be ported to the new code...

Then, I would file these issues:
* add support for images in df export (Base64 is not supported, we need GIF or JPG)
* #208 for df export
* add support for stardict and mobi in the CI via pyglossary command line, or in another step and then in the CI

**Comment by BoboTiG** [comment]
This is good. As soon as the original Kobo dict is full featured, we can have other dictionaries not yet at the same level.

**Review by BoboTiG — APPROVED** [review]

**Comment by BoboTiG** [comment]
Thanks a lot for your work @lasconic :) 🍾

**Pull request merged**
