### PR TITLE
fix #1500: Output unknown template as it

### LINKED ISSUE #1500: [FR] What do with such template?
- Wiktionary page: https://fr.wiktionary.org/wiki/reparasiter

Wikicode:
```
{{[[re-]]}}
```

Output:
```
<i>(Re-)</i>
```

Expected:
```
{{[re-](https://fr.wiktionary.org/wiki/re-)}}
```

Should we try to extract `[[re-]]` from the `{{}}` in `clean()`? :thinking:

### PR DESCRIPTION
**Pull request by lasconic**
Fixes #1500

### CODE REVIEW

**Comment by lasconic** [comment]
As I said, it's ugly...

**Comment by BoboTiG** [comment]
Well, why not :D

**Comment by lasconic** [comment]
I tried to fix as much as I could of missing template in french, running check words up for all words starting with A, B and large part of C. But we would need to do the same for other languages...

**Comment by BoboTiG** [comment]
I'll copy the patch locally to be able to run the CI on it.

**Comment by BoboTiG** [comment]
Ah I see, no output for missing templates ...
Let's merge and tackle missing templates when we have time.

I'll run `--check-words` on other locales (EN last).

**Comment by BoboTiG** [comment]
Ready to merge @lasconic ?

**Pull request merged**
