### PR TITLE
[FR] Clean-up last_template_handler()

### PR DESCRIPTION
**Pull request by BoboTiG**
- Sorted doctests.
- Sorted conditions.
- Always use `extract_keywords_from()`.
- Removed useless comments.

- [ ] Fixes #
- [x] Tests added/updated.
- [x] `./check.sh` run and eventual issues fixed.
- [ ] Updated CONTRIBUTORS.md, if not already done in the past.

### CODE REVIEW

**Comment by BoboTiG** [comment]
that function is becoming big, let's try to ease future changes.

**Review by lasconic — APPROVED** [review]

**Comment by lasconic** [comment]
Mmm this is not good. We have a lot of errors now. See the word "comme"

```
  File "ebook-reader-dict/scripts/lang/fr/__init__.py", line 973, in last_template_handler
    phrase = italic(parts.pop(0))
IndexError: pop from empty list
```

**Comment by BoboTiG** [comment]
Checking right now.

**Comment by BoboTiG** [comment]
Fix pushed.

**Pull request merged**
