### PR TITLE
[DE] Correct gender regex, separators, release info text.

### PR DESCRIPTION
**Pull request by Moonbase59**
Fixes #1176

### CODE REVIEW

**Comment by BoboTiG** [comment]
Thanks @Moonbase59 !

Could you fix the conflict? I guess you did not sync your fork before working on that PR?

**Comment by Moonbase59** [comment]
Yes, I guess you might have been working on it at the same time and got a few commits ahead. Now let me read up on how to sync everything up using git…

**Comment by Moonbase59** [comment]
Sorry for the dumb questions, but it’s a looong time I collaborated, usually only working on my own repos…

I’ve now synced my master to yours, but my branch "release-info" still says "This branch is 2 commits ahead, 6 commits behind BoboTiG:master." How do I safely get your changes into my branch without loosing my changes? So this can be resolved?

**Comment by lasconic** [comment]
in your branch,

```
git rebase master
```

fix the conflicts, git add the file  and

```
git rebase --continue
```

But we don't need the two commits here only the second one no ?

**Comment by Moonbase59** [comment]
Thanks for the help @lasconic. I was impatient and did

```bash
git checkout release-info
git fetch origin
git merge origin/master
(conflict, edited file)
git add wikidict/lang/de/__init__.py
git commit -m "resolve merge conflict"
git push
```

Looks a little clumsy, but I had something about a "loose HEAD" and it seems to have worked. Comments how to make it better in the future?

**Comment by lasconic** [comment]
Next time you should create a new branch for each fix  based on mastter

**Comment by Moonbase59** [comment]
> Next time you should create a new branch for each fix based on mastter

That’s what I originally did—and then didn’t know how to get your updates into it. Plus, the web page said "push to Moonbase…/release-info…" :-)

Live and learn! Even at my age, hee hee. Thanks for your help!

**Comment by BoboTiG** [comment]
When a commit is merged on the main repository, you can use the "Fetch upstream" button on your fork:
Untitled

**Comment by Moonbase59** [comment]
Would this be the same as doing a

```bash
git fetch upstream
git checkout master
git merge upstream/master
```
?

**Comment by BoboTiG** [comment]
You could even do:

```shell
git checkout master
git pull upstream master
```

**Pull request merged**
