### PR TITLE
Log only once a missing template

### PR DESCRIPTION
**Pull request by BoboTiG**
- [x] Related to #257
- [ ] Tests added/updated.
- [x] `./check.sh` run and eventual issues fixed.
- [x] Updated CONTRIBUTORS.md, if not already done in the past.

### CODE REVIEW

**Comment by lasconic** [comment]
Yes. It will reduce the log quite a lot but we will not be able to sort the templates by "priority".

**Comment by BoboTiG** [comment]
I wanted to use a `Counter` first, but it requires more work (not much). I can still try it, WDYT?

**Comment by lasconic** [comment]
we can do it when we tackle english or spanish ;)

**Comment by BoboTiG** [comment]
I am not sure the counter is necessary as we _should_ handle all templates, occurrences should not really matter. (And mostly because the code is simple as-is haha).

**Comment by BoboTiG** [comment]
OK, let's keep as-si and see how it will be for other locales :)

**Review by lasconic — APPROVED** [review]

**Pull request merged**
