### PR TITLE
fix #1411: [FR] Add support for the 'ar-terme' template

### LINKED ISSUE #1411: [FR] Add support for the 'ar-terme' template
- Wiktionary page: https://fr.wiktionary.org/wiki/Muad-Dib
- Model link, if any: https://fr.wiktionary.org/wiki/Mod%C3%A8le:ar-terme

### PR DESCRIPTION
**Pull request by lasconic**
Fixes #1411

### CODE REVIEW

**Review by BoboTiG — APPROVED** [review]

**Comment by BoboTiG** [comment]
💪

**Comment by lasconic** [comment]
Before merge, I would like to handpick some of sourcery suggestions.

**Comment by lasconic** [comment]
But that will be for later, maybe next week.

**Comment by BoboTiG** [comment]
Your PR, your call :)

**Pull request merged**
