### PR TITLE
Handle the <math> HTML tag (closes #54)

### LINKED ISSUE #54: Handle the <math> HTML tag
Wiktionary page: https://fr.wiktionary.org/wiki/octonion

Wikicode:
```
<math>x=x_0+x_1{\rm i}+x_2{\rm j}+x_3{\rm k}+x_4{\rm l}+x_5{\rm il}+x_6{\rm jl}+x_7{\rm kl}</math>
```

Output:
```
x=x_0+x_1{\rm i}+x_2{\rm j}+x_3{\rm k}+x_4{\rm l}+x_5{\rm il}+x_6{\rm jl}+x_7{\rm kl}
```

Expected:
```
Not sure if we can and how to display it.
```

### PR DESCRIPTION
**Pull request by BoboTiG**
- [x] Fixes #54
- [x] Tests added/updated.
- [x] `./check.sh` run and eventual issues fixed.
- [x] Updated CONTRIBUTORS.md, if not already done in the past.

Are a screenshots, this is quite neat :)

screen_001
screen_004
screen_006
screen_007

### CODE REVIEW

**Review by lasconic — COMMENTED** [review]
My dev env is on MacOS. I will try to find a way to install dvipng and latex. I guess it needs to be documented somewhere.

**Comment by BoboTiG** [comment]
```shell
brew cask install mactex-no-gui
```

**Comment by BoboTiG** [comment]
Hop: https://github.com/BoboTiG/ebook-reader-dict/wiki/HOWTO-Install-LaTeX-and-dvipng-to-handle-the--math--HTML-tag

**Comment by lasconic** [comment]
Thanks. It works.

**Comment by BoboTiG** [comment]
Good to merge then?

**Comment by lasconic** [comment]
Still testing :)

**Comment by lasconic** [comment]
I see 3 errors in the french fetch phase

<math> ERROR with <re.Match object; span=(27, 84), match='<math> |\\langle x,y\\rangle|\\leqslant \\|x\\|\\>
<math> ERROR with <re.Match object; span=(96, 138), match='<math> 0 \\leqslant x \\leqslant 0,7 <
<math> ERROR with <re.Match object; span=(74, 91), match='<math>\\R^n<

Here is a list of words with `<math>` in french  https://gist.github.com/lasconic/f740c1b77acb07b7ddef221e6f09c22f

**Comment by BoboTiG** [comment]
I was aware of those 3 errors, but they are out of our power. The third one is about an unknown symbol in the font. Maybe this will be fixed in later versions of LaTeX, or not. In any cases, the word is still handled and the formula inserted in the definition. So we do not lose anything.

For 1 and 2, it may be where the regex stops the search. It will go until the "<" character is found. I'll look into it.

**Comment by lasconic** [comment]
Some more in english : https://gist.github.com/lasconic/75ffae4499da73edc59b3f34b9d6dd72

**Comment by lasconic** [comment]
I'm far from fluent in LaTeX but I believe there is a problem with backslashes or escape chars, no?

**Comment by BoboTiG** [comment]
Same for me. I am looking for a solution ⌛

**Comment by BoboTiG** [comment]
WDYT of merging this PR and improve the support later (if possible)?

**Comment by lasconic** [comment]
let's go

**Pull request merged**
