### PR TITLE
Convert namespaces to regular templates

### LINKED ISSUE #1494: Smarter link-with-namespace filter
- Wiktionary page: https://fr.wiktionary.org/wiki/halq%E2%80%99em%C3%A9ylem

Wikicode:
```
[[Stó:lō]]
```

Output:
```
None
```

Expected:
```
Stó:lō
```

The wikicode is stripped at https://github.com/BoboTiG/ebook-reader-dict/blob/fdca309f31290fdee99fe76efb2b2f33b45112c1/wikidict/utils.py#L391

Not sure what to do for now, just reporting the issue.

### PR DESCRIPTION
**Pull request by BoboTiG**
Fixes #1494

Another proposal. It requires more code, and we will need to handle new templates when we discover them.

### CODE REVIEW

**Comment by BoboTiG** [comment]
The update job is [running)[https://github.com/BoboTiG/ebook-reader-dict/actions/runs/3937907482] to catch missing templates. If that works for you @lasconic, I'll just add them when it's finished.

**Comment by BoboTiG** [comment]
I like the current idea, mostly because when the one-time job to handle new templates will be done, it's almost fully automated for upcoming namespace changes (even if it's unlikely to happen on a regular basis).
If we go with special treatments in `clean()` (I am not opposed to such idea), we'll need to keep a list of namespaces to handle, and another one with ignored ones. I don't know if it's better, worse, or the same.
What I propose: I finish that version, just to have a complete overview of what if requires as code; and you may find some time to try another version. WDYT?

> Also, let's hope we don't have actual templates with the same name than namespace...

It seems we are lucky enough: those templates always start with a capital letter. It should be OK.

**Comment by BoboTiG** [comment]
> > Also, let's hope we don't have actual templates with the same name than namespace...
> 
> It seems we are lucky enough: those templates always start with a capital letter. It should be OK.

OK, that's not true for italian, at least. But it doesn't mess with current templates either.

**Comment by BoboTiG** [comment]
I moved out from `last_template_handler()` in https://github.com/BoboTiG/ebook-reader-dict/pull/1518/commits/89c61bc3228f6c3309fbcdfa7ed2c3ee38181c6a, better now.

I'm surprised that english is not using any namespaces.

The last patch for German will come soon.

**Comment by lasconic** [comment]
The wiktionary API gave back the "canonical" namespace name in english 
https://es.wiktionary.org/w/api.php?action=query&meta=siteinfo&siprop=namespaces

I guess if Fichier needs to be handled differently, then in other languages all namespaces with canonical "File" will have to as well.

**Comment by BoboTiG** [comment]
Given the "missing template" line reported by the CI, for now no need to handle more templates.
I started another [job](https://github.com/BoboTiG/ebook-reader-dict/actions/runs/3938646113) just to be sure nothing is missing.

**Comment by BoboTiG** [comment]
Do you plan to work on another solution? Or let's put it like that: do you dislike that proposal enough to reject the patch? :)

**Comment by lasconic** [comment]
Trying something shorter as we speak

**Comment by BoboTiG** [comment]
Superseded by #1530.

**Pull request closed without merging**
