### PR TITLE
fix #703: support 'hiero' extension

### LINKED ISSUE #703: Support <hiero> mediawiki extension
- Wiktionary page: https://fr.wiktionary.org/wiki/djed

Wikicode:
```
<hiero>R11</hiero>
```

Output:
```
R11
```

Expected:
```

```

---

Model link, if any: https://www.mediawiki.org/wiki/Extension:WikiHiero
https://www.mediawiki.org/wiki/Special:MyLanguage/Extension:WikiHiero/Syntax
https://github.com/wikimedia/mediawiki-extensions-wikihiero/blob/366b1226891e609650b4c7f7d925b718c779517c/includes/WikiHiero.php

### PR DESCRIPTION
**Pull request by lasconic**
Fixes #703

### CODE REVIEW

**Comment by BoboTiG** [comment]
That's amazing :champagne:

I would say tests would be very interesting, at least to ensure it is working as expected, but also to keep coverage at 100%. If possible :)

**Comment by lasconic** [comment]
I will try to add some tests. Support for mirrored element is not implemented yet.

**Comment by lasconic** [comment]
Tests are back to 99%, mirror is in. A bit more work to put the text to 100%

**Comment by lasconic** [comment]
Tests are 100%. Only the vertical alignment problem remains.

**Comment by BoboTiG** [comment]
I am OK to merge it when you want. The vertical alignment could be tackled later, if you prefer ;)

**Comment by lasconic** [comment]
I tried a lot of different approach for the vertical alignment. It works on Chrome and Firefox and I couldn't find why it doesn't on kobo... Let's merge then

**Comment by lasconic** [comment]
Feel free to move hiero and hiero_utils somewhere else btw.

**Comment by BoboTiG** [comment]
> I tried a lot of different approach for the vertical alignment. It works on Chrome and Firefox and I couldn't find why it doesn't on kobo...

Then let's forget it. The current code is way above expectations :) 💪

**Pull request merged**
