### PR TITLE
Accurate missing template reporting

### PR DESCRIPTION
**Pull request by BoboTiG**
A proposal to ease our work for #1535.

It's not so simple (tests are not passing yet), but WDYT about such approach @lasconic?

### CODE REVIEW

**Comment by lasconic** [comment]
Not sure.
One thing, last template handler in defaults is not used by EN.

**Comment by BoboTiG** [comment]
Let's do the manuel hack, it will be good enough.

**Comment by lasconic** [comment]
If we want to make it a bit better, we could add a debug flag to guard the manual hack (or use a true logger ?)

**Comment by BoboTiG** [comment]
The true logger option is interesting :)

**Pull request closed without merging**
