### PR TITLE
fix #801: [ES] fix support for 'etim' template

### LINKED ISSUE #801: [ES] Fix support for 'etim' template
- Wiktionary page: https://es.wiktionary.org/w/index.php?title=hematidrosis

Wikicode:
```
{{etim|grc|ἱδρώς|sudor}}
```

Output:
```
del griego antiguo <i>sudor</i>
```

Expected:
```
del griego antiguo <i>ἱδρώς</i> ("sudor")
```

---

Model link, if any: https://es.wiktionary.org/w/index.php?title=Plantilla:etim

### PR DESCRIPTION
**Pull request by lasconic**
- [x] Fixes #801
- [x] Tests added/updated.
- [x] `./check.sh` run and eventual issues fixed.
- [x] Updated CONTRIBUTORS.md, if not already done in the past.

### CODE REVIEW

**Comment by BoboTiG** [comment]
A test would have been appreciated ;)

**Comment by lasconic** [comment]
Test to come

**Comment by lasconic** [comment]
Voilà :)

**Review by BoboTiG — APPROVED** [review]
Super ! :)

**Pull request merged**
