### PR TITLE
download: show file size when fetching, and start over if file is incomplete

### PR DESCRIPTION
**Pull request by ilius**
- Show file size/length when fetching
- Start over if file is incomplete (fetch cancelled)

### CODE REVIEW

**Comment by BoboTiG** [comment]
Thanks for the PR, I really like the idea :)

**Comment by ilius** [comment]
Switched to `requests.head()`, fixed tests and added 2 new tests.
`wikidict.utils.process_templates` is still failing on my machine though.

**Comment by BoboTiG** [comment]
I'll have a deeper look ASAP, should be good by Monday.

**Comment by ilius** [comment]
I actually rather use an external downloader like `wget` that can resume, since our internet is slow and unstable.

You can use my branch if you like.

**Comment by BoboTiG** [comment]
Actually, a resume feature would be interesting. I'll work on it later, thanks for the initial patch!

**Pull request closed without merging**
