### PR TITLE
fix #643: [FR] Add support for the 'ar-cf' template

### LINKED ISSUE #643: [FR] Add support for the 'ar-cf' template
- Wiktionary page: https://fr.wiktionary.org/wiki/Mourad
- Model link: https://fr.wiktionary.org/wiki/Mod%C3%A8le:ar-cf

### PR DESCRIPTION
**Pull request by lasconic**
Fixes #643

### CODE REVIEW

**Comment by BoboTiG** [comment]
That's awesome.
(I thought you would have introduced a `lua2python` script :trollface:)

**Review by BoboTiG — APPROVED** [review]

**Comment by lasconic** [comment]
Oh man... I thought about it but concluded it needs more than just regexp and string processing...
I should have asked chatGPT :) Let's me try it when he is back online.

**Comment by BoboTiG** [comment]
Oh ChatGPT! It could be interestring to see what will come out :)

**Comment by lasconic** [comment]
It's not that bad :) Trying with ar-IPA and ar-translit. I will report there.

**Pull request merged**
