### PR TITLE
Simplify pyglossary command

### PR DESCRIPTION
**Pull request by ilius**
`pyglossary --ui=none ...` works as intended (for ci / automation) since 4.1.0.

Also you may consider using language codes as part of input file name (like `dict-en-fr.df`) or change the `bookname` manually in `.ifo` file, so that GoldenDict can detect and show the 2 languages.

### CODE REVIEW

**Comment by BoboTiG** [comment]
Thanks @ilius ! :)

**Comment by BoboTiG** [comment]
@all-contributors please add @ilius for infra.

**Comment by BoboTiG** [comment]
About the naming, it is a one-language dictionnary, and we are already using the name as part of the file name: `dict-${{ matrix.locale }}.df` where `${{ matrix.locale }}` will result in "en", "fr", etc.
Isn't it enough?

**Comment by ilius** [comment]
I think GoldenDict may require two language codes to detect.
Better to use `en-en` or `fr-fr`.
It's also more common.
The first is source (query) language, second is target (definition) language.

**Comment by BoboTiG** [comment]
Do you mind proposing a PR that would fix GoldenDict support?

**Comment by ilius** [comment]
Sure.

**Pull request merged**
