### PR TITLE
Ease tracking of unsupported templates

### PR DESCRIPTION
**Pull request by BoboTiG**
Do you think it is worth flooding the console? :)

- [x] Related to #257
- [x] Tests added/updated.
- [x] `./check.sh` run and eventual issues fixed.
- [x] Updated CONTRIBUTORS.md, if not already done in the past.

### CODE REVIEW

**Comment by BoboTiG** [comment]
If you are OK, I will rebase after #266.

**Comment by lasconic** [comment]
In french, the flood will be soon very small ;) Any way to add an option ?

**Comment by BoboTiG** [comment]
Maybe a simple envar? We already have `CI` and `DEBUG`.

**Comment by lasconic** [comment]
Yes. Sounds good.

**Comment by BoboTiG** [comment]
Ready for a second review :)

**Review by lasconic — APPROVED** [review]

**Pull request merged**
